REQ_OP_SERVER_COMMAND = "Command"
REQ_OP_USER_COMMAND = "UserCommand"

USERCMD_TPS = "ShowTps"
USERCMD_LIST_PLAYER = "ListPlayers"
USERCMD_INTERACTION = "Pat"

ANIM_NONE = 0
ANIM_SHAKE_SCREEN = 1 << 0

PAT_SUCCESS = 0
PAT_OFFLINE_PLAYER = 1
